### ISSUE TITLE
Doesn't execute commands within a transaction

### ISSUE THREAD

**Issue by stevencdavis** [ckuttruff/clj-sql-up#14]
Although the migrations are using `sql/db-transaction*`, when MySQL errors are encountered and throw exceptions, previous commands within a migration file still get committed (as well as the migration id).

**Comment by ckuttruff** [comment]
Steven,

Thanks for bringing this to my attention.  I'll try my best to take a look after work.

Best,
-Chris

**Comment by ckuttruff** [comment]
Steven, 

Really sorry for the delay; my schedule has been a bit crazy lately (just got back from 9 days of camping in WA).

I'm going to set a reminder to look into this later, but given my time obligations at the moment, it might be a couple weeks.

Sorry again for the slowness on my part; I can def. prioritize PR review if you want to take a stab at submitting a PR.

Cheers,
-Chris

**Comment by ckuttruff** [comment]
Haha, sorry very late on a reply here but this is actually a fundamental limitation of mysql. 

See details here:
https://dev.mysql.com/doc/refman/5.7/en/cannot-roll-back.html

Gonna close, but please feel free to reopen if you feel I've missed something here.

Thanks!
