### ISSUE TITLE
Make migration dir configurable in lein plugin

### ISSUE THREAD

**Issue by fluxlife** [ckuttruff/clj-sql-up#15]
I like using the lein plugin part, but don't know how to load migrations from classpath. Would be nice if I could just add that to the config.

**Comment by ckuttruff** [comment]
haven't done this before, but is this what you're looking for?
https://github.com/ckuttruff/clj-sql-up/pull/13

Looks like someone has already kindly added this functionality :)
Please go ahead and close if this works out for you; thanks!

**Comment by fluxlife** [comment]
I noticed that the var was dynamic so I thought perhaps something like this existed, however I think what I am asking for is a little different.  

First, I must disclaim I am new to Clojure, so I apologize in advance if my request is out of turn. It is my understanding the dynamic var can be binded or altered when the application is started (just as it is described in #13) however, I want to run these migrations outside of the application ...more specifically as part of the clj-sql-up lein plugin. I soon realized after posting this, I do not need to load things from the classpath, but I still want to specify a migration dir for use in the lein plugin.

As I said earlier I am still a Clojure noob but I attempted a PR #16. Please let me know what you think.

**Comment by fluxlife** [comment]
Hi @ckuttruff, sorry to bug you but have you had any chance to check out PR #16 (re: custom migration folder via option in config)

**Comment by ckuttruff** [comment]
Really sorry, but I'm currently in Paris until December 14th and don't have
access to reliable wifi or a laptop with proper access.

I'll check this out in a week once I do

**Comment by fluxlife** [comment]
Thanks for the quick response. Sounds good! Have fun!

**Comment by ckuttruff** [comment]
Hey, so sorry.  I commented on that PR and will be testing things out tonight (set a reminder this time :)

Gonna go ahead and close this and resume discussion over there.

Thanks again for your contribution and sorry again for failing to review.  Looks like useful functionality
